/*****************************************************************
                        ABSENTEÍSMO

BASE DE HORAS TRABALHADAS
VERSÃO: 03 ÚLTIMA MODIFICAÇÃO EM 28/09/2023

******************************************************************/

SELECT PPESSOA.CODIGO AS COD_PESSOA,
       CASE
            WHEN PFUNC.CHAPA LIKE 'T%' THEN 'XXXXX'
            WHEN PFUNC.CHAPA LIKE 'B%' THEN 'XXXXX'
            WHEN PFUNC.CHAPA LIKE 'C%' THEN 'XXXXX'
            WHEN PFUNC.CHAPA LIKE 'A%' THEN 'XXXXX'
            WHEN PFUNC.CHAPA LIKE 'D%' THEN 'XXXXX'
            ELSE PFUNC.CHAPA END AS CHAPA,
       pfunc.NOME AS NOME,
       CASE
            WHEN PFUNCAO.NOME <> 'INSTRUTOR DE FORMAÇÃO PROFISSIONAL'
             AND PFUNCAO.NOME <> 'INSTRUTOR DE FORMACAO PROFISSIONAL'
             AND PFUNCAO.NOME <> 'ORIENT. DE CURSOS - INTERP. DE LIBRAS'
             AND PFUNCAO.NOME <> 'ORIENTADOR DE CURSOS'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR I'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR II'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR III'
             AND PFUNCAO.NOME <> 'SUPERVISOR DE ESTÁGIO'
             AND PFUNCAO.NOME <> 'SUPERVISOR DE ESTAGIO' THEN 'ADMINISTRATIVO'
            ELSE 'DOCENTE' END AS CLASSIFICACAO,
       PFUNC.CODSITUACAO AS 'COD_SITUACAO',
       CASE
            WHEN PFUNC.CODSITUACAO = 'A' THEN 'ATIVO'
            WHEN PFUNC.CODSITUACAO = 'D' THEN 'DEMITIDO'
            WHEN PFUNC.CODSITUACAO = 'E' THEN 'LICENCA MATERNIDADE'
            WHEN PFUNC.CODSITUACAO = 'F' THEN 'FERIAS'
            WHEN PFUNC.CODSITUACAO = 'I' THEN 'APOSENTADO INVALIDEZ'
            WHEN PFUNC.CODSITUACAO = 'L' THEN 'LICENCA SEM REMUNERACAO'
            WHEN PFUNC.CODSITUACAO = 'P' THEN 'AFASTADO INSS'
            WHEN PFUNC.CODSITUACAO = 'R' THEN 'LICENCA REMUNERADA'
            WHEN PFUNC.CODSITUACAO = 'T' THEN 'ACIDENTE TRABALHO'
            WHEN PFUNC.CODSITUACAO = 'V' THEN 'AVISO PREVIO'
            WHEN PFUNC.CODSITUACAO = 'Y' THEN 'LICENCA PATERNIDADE'
            WHEN PFUNC.CODSITUACAO = 'Z' THEN 'ADMISSAO PROXIMO MES'
            WHEN PFUNC.CODSITUACAO = 'C' THEN 'CONTRATO SUSPENSO'
            WHEN PFUNC.CODSITUACAO = 'G' THEN 'ESTAGIO RECESSO'
            WHEN PFUNC.CODSITUACAO = 'K' THEN 'SESSAO REQUISIÃ‡ÃƒO'
            WHEN PFUNC.CODSITUACAO = 'M' THEN 'SERVICO MILITAR'
            WHEN PFUNC.CODSITUACAO = 'N' THEN 'MANDATO SINDICAL'
            WHEN PFUNC.CODSITUACAO = 'O' THEN 'DOENCA OCUPACIONAL'
            WHEN PFUNC.CODSITUACAO = 'Q' THEN 'PRISSAO/CÁRCERE'
            WHEN PFUNC.CODSITUACAO = 'S' THEN 'MANDATO SINDICAL'
            WHEN PFUNC.CODSITUACAO = 'U' THEN 'OUTROS'
            WHEN PFUNC.CODSITUACAO = 'W' THEN 'LICENCA MATERNIDADE COMP.180'
            WHEN PFUNC.CODSITUACAO = 'X' THEN 'C/ DEMISSÃO NO MES'
            ELSE 'NULL' END AS 'SITUACAO',
       ANOCOMP AS ANO,
       MESCOMP AS MES,
       FORMAT(PFFINANC.DTPAGTO, 'dd/MM/yyyy') AS DATA_REF,
       concat('01/', MESCOMP, '/', ANOCOMP) AS DATA_,
       PFFINANC.NROPERIODO AS 'PER.',
       CASE
            WHEN PFFINANC.NROPERIODO = 1 THEN 'ADIANTAMENTO'
            WHEN PFFINANC.NROPERIODO = 2 THEN 'FOLHA DE PAGAMENTO'
            WHEN PFFINANC.NROPERIODO = 3 THEN 'DIFERENÇA SALARIAL'
            WHEN PFFINANC.NROPERIODO = 4 THEN 'RESCISÃO'
            WHEN PFFINANC.NROPERIODO = 4 THEN 'RESCISÃO'
            ELSE ' ' END AS PERIODO,


       --	PFUNC.CODRECEBIMENTO AS 'REGIME HS',

       CASE
            WHEN PFUNC.CODRECEBIMENTO = 'M' THEN 'MENSALISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'P' THEN 'HORISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'H' THEN 'INTERMITENTE'
            WHEN PFUNC.CODRECEBIMENTO = 'D' THEN 'DIARISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'T' THEN 'TAREFEIRO'
            WHEN PFUNC.CODRECEBIMENTO = 'O' THEN 'OUTROS'
            WHEN PFUNC.CODRECEBIMENTO = 'Q' THEN 'QUINZENALISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'S' THEN 'SEMANALISTA'
            ELSE 'NULL' END AS 'RECEBIMENTO',
       PEVENTO.CODIGO as CODEVENTO,
       PEVENTO.DESCRICAO AS 'DESCRIÇÃO EVENTO',
       PFFINANC.REF AS 'HR DP',
       PFUNC.JORNADAMENSAL / 60 AS 'HR QP',
       CASE
            WHEN PFUNC.CODRECEBIMENTO IN ( 'P', 'H' ) THEN PFFINANC.REF
            --when PFUNC.CODRECEBIMENTO = 'M' THEN cast(((PFUNC.JORNADAMENSAL/30 * PFFINANC.REF) / 60) as numeric(15, 2))
            when PFUNC.CODRECEBIMENTO = 'M' THEN PFUNC.JORNADAMENSAL / 60 END AS 'CARG_HOR_TRAT.',
       PSECAO.CODIGO AS CODIGO_SECAO
  FROM PFFINANC
 INNER JOIN PEVENTO
    ON PFFINANC.CODCOLIGADA   = PEVENTO.CODCOLIGADA
   AND PFFINANC.CODEVENTO     = PEVENTO.CODIGO
 INNER JOIN PFUNC
    ON PFFINANC.CODCOLIGADA   = PFUNC.CODCOLIGADA
   AND PFFINANC.CHAPA         = PFUNC.CHAPA
 INNER JOIN PSECAO
    ON PSECAO.CODCOLIGADA     = PFUNC.CODCOLIGADA
   AND PSECAO.CODIGO          = PFUNC.CODSECAO
  LEFT OUTER JOIN PPESSOA (NOLOCK)
    ON ((PFUNC.CODPESSOA      = PPESSOA.CODIGO))
  LEFT OUTER JOIN TABAGP (NOLOCK)
    ON (   (PFUNC.CODCOLIGADA = TABAGP.CODCOLIGADA)
     AND   (PFUNC.CODSECAO    = TABAGP.COD_PK))
  LEFT OUTER JOIN PFUNCAO (NOLOCK)
    ON (   (PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
     AND   (PFUNC.CODFUNCAO   = PFUNCAO.CODIGO))
 WHERE PFFINANC.ANOCOMP > '2021'
   AND PFFINANC.MESCOMP in ( '01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12' )
   AND PFFINANC.CODEVENTO IN ( '0001', '0002', '0105', '0425', '443', '0473', '0514', '0525', '0536', '0537', '0538',
                               '0610', '0667', '0678', '0680', '0682', '0737', '0738', '0748', '0760', '0778', '0779',
                               '0780', '0781', '0782', '0783', '0784', '0785', '0786', '0794' )



