
/*****************************************************************
                        ABSENTEÍSMO

BASE DE ABONOS 
VERSÃO: 03 ÚLTIMA MODIFICAÇÃO EM 28/09/2023

******************************************************************/

USE CORPORE

SELECT 
ABONO.DATA_REF,
ABONO.CODIGO_SECAO,
ABONO.COD_PESSOA,
ABONO.CHAPA, 
ABONO.NOME, 
ABONO.CLASSIFICACAO,  
ABONO.SITUACAO,
ABONO.RECEBIMENTO,
ABONO.COD_ABONO,
ABONO.DESCRICAO_ABONO,
ABONO.CLASSIFICACAO_ABS,
ABONO.TIPO_ABONO_TRATADO,
ABONO.ABONO,
ABONO.TOTAL,

CASE 
    WHEN ABONO.TRATAMENTO = '3,5' then '3,50'
    ELSE CAST(ABONO.HR_FINAL AS varchar(5))
END AS 'HORA FINAL'



FROM

(
SELECT PPESSOA.CODIGO AS COD_PESSOA,
       AABONFUN.CHAPA AS CHAPA,
       PFUNC.NOME AS NOME,
       CASE
            WHEN PFUNCAO.NOME <> 'INSTRUTOR DE FORMAÇÃO PROFISSIONAL'
             AND PFUNCAO.NOME <> 'INSTRUTOR DE FORMACAO PROFISSIONAL'
             AND PFUNCAO.NOME <> 'ORIENT. DE CURSOS - INTERP. DE LIBRAS'
             AND PFUNCAO.NOME <> 'ORIENTADOR DE CURSOS'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR I'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR II'
             AND PFUNCAO.NOME <> 'PROFESSOR DE ENSINO SUPERIOR III'
             AND PFUNCAO.NOME <> 'SUPERVISOR DE ESTÁGIO'
             AND PFUNCAO.NOME <> 'SUPERVISOR DE ESTAGIO' THEN 'ADMINISTRATIVO'
            ELSE 'DOCENTE' END AS CLASSIFICACAO,
       PFUNC.CODSITUACAO AS COD_SITUACAO,
       CASE
            WHEN PFUNC.CODSITUACAO = 'A' THEN 'ATIVO'
            WHEN PFUNC.CODSITUACAO = 'D' THEN 'DEMITIDO'
            WHEN PFUNC.CODSITUACAO = 'E' THEN 'LICENCA MATERNIDADE'
            WHEN PFUNC.CODSITUACAO = 'F' THEN 'FERIAS'
            WHEN PFUNC.CODSITUACAO = 'I' THEN 'APOSENTADO INVALIDEZ'
            WHEN PFUNC.CODSITUACAO = 'L' THEN 'LICENCA SEM REMUNERACAO'
            WHEN PFUNC.CODSITUACAO = 'P' THEN 'AFASTADO INSS'
            WHEN PFUNC.CODSITUACAO = 'R' THEN 'LICENCA REMUNERADA'
            WHEN PFUNC.CODSITUACAO = 'T' THEN 'ACIDENTE TRABALHO'
            WHEN PFUNC.CODSITUACAO = 'V' THEN 'AVISO PREVIO'
            WHEN PFUNC.CODSITUACAO = 'Y' THEN 'LICENCA PATERNIDADE'
            WHEN PFUNC.CODSITUACAO = 'Z' THEN 'ADMISSAO PROXIMO MES'
            WHEN PFUNC.CODSITUACAO = 'C' THEN 'CONTRATO SUSPENSO'
            WHEN PFUNC.CODSITUACAO = 'G' THEN 'ESTAGIO RECESSO'
            WHEN PFUNC.CODSITUACAO = 'K' THEN 'SESSAO REQUISIÃ‡ÃƒO'
            WHEN PFUNC.CODSITUACAO = 'M' THEN 'SERVICO MILITAR'
            WHEN PFUNC.CODSITUACAO = 'N' THEN 'MANDATO SINDICAL'
            WHEN PFUNC.CODSITUACAO = 'O' THEN 'DOENCA OCUPACIONAL'
            WHEN PFUNC.CODSITUACAO = 'Q' THEN 'PRISSAO/CÁRCERE'
            WHEN PFUNC.CODSITUACAO = 'S' THEN 'MANDATO SINDICAL'
            WHEN PFUNC.CODSITUACAO = 'U' THEN 'OUTROS'
            WHEN PFUNC.CODSITUACAO = 'W' THEN 'LICENCA MATERNIDADE COMP.180'
            WHEN PFUNC.CODSITUACAO = 'X' THEN 'C/ DEMISSÃO NO MES'
            ELSE 'NULL' END AS 'SITUACAO',
       PFUNC.CODRECEBIMENTO AS COD_RECEBIMENTO,
       CASE
            WHEN PFUNC.CODRECEBIMENTO = 'M' THEN 'MENSALISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'P' THEN 'HORISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'H' THEN 'INTERMITENTE'
            WHEN PFUNC.CODRECEBIMENTO = 'D' THEN 'DIARISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'T' THEN 'TAREFEIRO'
            WHEN PFUNC.CODRECEBIMENTO = 'O' THEN 'OUTROS'
            WHEN PFUNC.CODRECEBIMENTO = 'Q' THEN 'QUINZENALISTA'
            WHEN PFUNC.CODRECEBIMENTO = 'S' THEN 'SEMANALISTA'
            ELSE 'NULL' END AS 'RECEBIMENTO',
       AABONFUN.CODABONO AS COD_ABONO,
       UPPER(AABONO.DESCRICAO) AS DESCRICAO_ABONO,
       CASE
            WHEN AABONFUN.CODABONO = 0000 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0001 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0013 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0014 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0015 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0016 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0029 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0031 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0056 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0057 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0058 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0063 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0065 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0064 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0066 THEN 'SAÚDE'
            WHEN AABONFUN.CODABONO = 0044 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0045 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0049 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0050 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0051 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0052 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0055 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0062 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0067 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0068 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0069 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0070 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0072 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0074 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0075 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0076 THEN 'LIBERALIDADE'
            WHEN AABONFUN.CODABONO = 0002 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0003 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0004 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0005 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0006 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0007 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0008 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0009 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0010 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0011 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0012 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0017 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0019 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0020 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0021 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0022 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0023 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0024 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0025 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0028 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0032 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0034 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0035 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0036 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = '0036' THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0037 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0038 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0039 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0040 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0041 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0043 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0053 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0054 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0059 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0061 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0071 THEN 'OUTROS'
            WHEN AABONFUN.CODABONO = 0073 THEN 'OUTROS'
            ELSE 'VERIFICAR!' END AS 'CLASSIFICACAO_ABS',
       CASE
            WHEN AABONFUN.CODABONO in ( 0020, 0023, 0025, 0022, 0021, 0024 ) THEN 'OBITO'
            WHEN AABONFUN.CODABONO in ( 0012, 0038, 0040, 0059, 0012, 0039, 0073, 0076 ) THEN 'ACOMPANHAMENTO MÉDICO'
            WHEN AABONFUN.CODABONO in ( 0000 ) THEN 'ATESTADO (DIA)'
            WHEN AABONFUN.CODABONO in ( 0003 ) THEN 'LICENCA PATERNIDADE'
            WHEN AABONFUN.CODABONO in ( 0005 ) THEN 'FALECIMENTO CONJ, PAIS E FILHOS'
            WHEN AABONFUN.CODABONO in ( 0006 ) THEN 'FALECIMENTO AVOS, IRMAOS E NETOS'
            WHEN AABONFUN.CODABONO in ( 0010 ) THEN 'SERVIÇO MILITAR'
            WHEN AABONFUN.CODABONO in ( 0066 ) THEN 'ATESTADO HORAS'
            WHEN AABONFUN.CODABONO in ( 0011 ) THEN 'LICENCA VESTIBULAR'
            WHEN AABONFUN.CODABONO in ( 0001, 0016, 0014, 0015 ) THEN 'ATESTADO MEDICO'
            WHEN AABONFUN.CODABONO in ( 0013, 0031, 0029 ) THEN 'ATESTADO ODONTOLOGICO'
            WHEN AABONFUN.CODABONO in ( 0074, 0075 ) THEN 'EXAME PERIODICO'
            WHEN AABONFUN.CODABONO in ( 0069 ) THEN 'AUSENCIA - PANDEMIA BAS/TEC'
            WHEN AABONFUN.CODABONO in ( 0070 ) THEN 'AUSENCIA ABONADA -  BAS/TEC'
            WHEN AABONFUN.CODABONO in ( 0067 ) THEN 'AUSENCIA ABONADA - GRUPO RISCO'
            WHEN AABONFUN.CODABONO in ( 0002, 0028 ) THEN 'CASAMENTO'
            WHEN AABONFUN.CODABONO in ( 0009, 0032, 0034, 0036 ) THEN 'COMPARECIMENTO A JUSTICA'
            WHEN AABONFUN.CODABONO in ( 0054 ) THEN 'CONVOCACAO SINDICAL'
            WHEN AABONFUN.CODABONO in ( 0063, 0064, 0065 ) THEN 'DECL - EXAME/CONSULTA'
            WHEN AABONFUN.CODABONO in ( 0058, 0056 ) THEN 'DECLARAÇÃO MÉDICA'
            WHEN AABONFUN.CODABONO in ( 0057 ) THEN 'DECLARAÇÃO ODONTOLÓGICA'
            WHEN AABONFUN.CODABONO in ( 0007 ) THEN 'DOAÇÃO DE SANGUE'
            WHEN AABONFUN.CODABONO in ( 0005, 0006 ) THEN 'FALECIMENTO FAMILIAR'
            WHEN AABONFUN.CODABONO in ( 0052, 0053 ) THEN 'FALTA ABONADA'
            WHEN AABONFUN.CODABONO in ( 0050 ) THEN 'FERIADO'
            WHEN AABONFUN.CODABONO in ( 0051 ) THEN 'FERIAS COLETIVAS/LIC. REMUN.'
            WHEN AABONFUN.CODABONO in ( 0049 ) THEN 'FERIAS PREMIO'
            WHEN AABONFUN.CODABONO in ( 0035, 0037, 0008, 0009 ) THEN 'JUSTIÇA ELEITORAL'
            WHEN AABONFUN.CODABONO in ( 0044 ) THEN 'LIBERAÇÃO EMPRESA'
            WHEN AABONFUN.CODABONO in ( 0004, 0043, 0041 ) THEN 'LICENCA AMAMENTACAO'
            WHEN AABONFUN.CODABONO in ( 0017, 0003, 0019 ) THEN 'LICENÇA PATERNIDADE'
            WHEN AABONFUN.CODABONO in ( 0045 ) THEN 'LICENÇA SEM VENCIMENTO'
            WHEN AABONFUN.CODABONO in ( 0061 ) THEN 'PANDEMIA COVID 19'
            WHEN AABONFUN.CODABONO in ( 0062 ) THEN 'RETORNO AO TRABALHO'
            WHEN AABONFUN.CODABONO in ( 0055 ) THEN 'RETORNO DE FERIAS PARTIDAS'
            WHEN AABONFUN.CODABONO in ( 0055 ) THEN 'RETORNO DE FERIAS PARTIDAS'
            WHEN AABONFUN.CODABONO in ( 0072 ) THEN 'RETORNO AO TRABALHO'
            WHEN AABONFUN.CODABONO in ( 0071 ) THEN 'TESTE DP'
            ELSE 'VERIFICAR' END AS 'TIPO_ABONO_TRATADO',
       AABONFUN.CODABONO + ' - ' + AABONO.DESCRICAO AS ABONO,
       dbo.FN_CONVMIN(SUM(ABS(AABONFUN.HORAFIM - AABONFUN.HORAINICIO))) AS TOTAL,
       CASE
            WHEN AABONFUN.HORAINICIO = '480'
             AND AABONFUN.HORAFIM = '1320' THEN '3,5'
            ELSE '0' END AS 'TRATAMENTO',
       CAST((CAST((((HORAFIM) - (HORAINICIO))) AS DECIMAL(5)) / 60) AS DECIMAL(18, 2)) AS 'HR_FINAL',


       FORMAT(AABONFUN.DATA, 'dd/MM/yyyy') AS DATA_REF,
       FORMAT(AABONFUN.DATA, '01/MM/yyyy') AS DATA_,
       PSECAO.CODIGO AS CODIGO_SECAO,
       PSECAO.DESCRICAO AS DESCRICAO_SECAO
  FROM AABONFUN (NOLOCK)
  JOIN AABONO (NOLOCK)
    ON AABONFUN.CODCOLIGADA   = AABONO.CODCOLIGADA
   AND AABONFUN.CODABONO      = AABONO.CODIGO
  JOIN PFUNC (NOLOCK)
    ON AABONFUN.CODCOLIGADA   = PFUNC.CODCOLIGADA
   AND AABONFUN.CHAPA         = PFUNC.CHAPA
  JOIN PSECAO (NOLOCK)
    ON PFUNC.CODCOLIGADA      = PSECAO.CODCOLIGADA
   AND PFUNC.CODSECAO         = PSECAO.CODIGO
  LEFT OUTER JOIN PPESSOA (NOLOCK)
    ON ((PFUNC.CODPESSOA      = PPESSOA.CODIGO))
  LEFT OUTER JOIN TABAGP (NOLOCK)
    ON (   (PFUNC.CODCOLIGADA = TABAGP.CODCOLIGADA)
     AND   (PFUNC.CODSECAO    = TABAGP.COD_PK))
  LEFT OUTER JOIN PFUNCAO (NOLOCK)
    ON (   (PFUNC.CODCOLIGADA = PFUNCAO.CODCOLIGADA)
     AND   (PFUNC.CODFUNCAO   = PFUNCAO.CODIGO))
 WHERE
    --((AABONFUN.HORAFIM-AABONFUN.HORAINICIO)>0) AND AABONFUN.DATA>='01/01/2022' AND AABONFUN.DATA<= GETDATE()
       ((AABONFUN.HORAFIM - AABONFUN.HORAINICIO) > 0)
   AND AABONFUN.DATA                             >= '01/01/2022'
   AND AABONFUN.DATA                             <= DATEADD(DAY, -1, EOMONTH(GETDATE(), -1))


   AND AABONFUN.CODABONO                         <> '0071'
 GROUP BY PSECAO.CODIGO,
          PFUNC.NOME,
          PSECAO.DESCRICAO,
          AABONFUN.CHAPA,
          AABONFUN.CHAPA,
          PFUNC.CODSITUACAO,
          AABONFUN.DATA,
          AABONFUN.CODABONO,
          AABONO.DESCRICAO,
          PFUNC.CODRECEBIMENTO,
          AABONFUN.HORAINICIO,
          AABONFUN.HORAfim,
          PPESSOA.CODIGO,
          PFUNCAO.NOME

		  ) AS ABONO


		  


